update flake

diff --git a/modules/packages/system/system b/modules/packages/system/system
--- a/modules/packages/system/system
+++ b/modules/packages/system/system
@@ -14,6 +14,7 @@ MAGENTA=$'\e[35m'
 main() {
   case "$1" in 
     rebuild) shift 1; rebuild "$@";;
+    build) shift 1; build "$@";;
     *) usage; exit 1 ;;
   esac
 }
@@ -40,6 +41,14 @@ info() {
   echo "${GREEN}[INFO]${RST}" "$@" >&2
 }
 
+build() {
+  pushd "$REPO" || fatal "Changing direcotry failed"
+
+  nixos-rebuild build --flake . "$@"
+
+  trap popd EXIT
+}
+
 rebuild() {
   local current_branch host_branch gen
 
@@ -61,7 +70,7 @@ rebuild() {
   git checkout --no-guess "$host_branch"
 
   #shellcheck disable=2064
-  trap "git checkout $current_branch" EXIT 
+  trap "git checkout $current_branch; popd" EXIT 
 
   info "Updating $host_branch from $current_branch"
   git restore --source="$current_branch" --worktree --staged .
